error:
  whitelabel:
    enabled: false

spring:
  jpa:
    hibernate:
      ddl-auto: none

---
spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://aa1awaszo27j09d.cnb0uevtgcxp.us-east-2.rds.amazonaws.com/ebdb
    username: CGschwend
    password: Garrison29
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

